remove old node code
elasticdao/sdk pull request #117
Opened 2021-10-25 17:44 UTC by lrsaturnino

##### Description
- Removes code associated to the old javascript node;
Closes #103 

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Test coverage hasn't decreased

2021-10-25 21:51 UTC, 0xean requested changes
This is a good start, but there is still code to removed I think. Please double check but the following should probably be able to be removed:

1. src/integrations/IPFS.js 
2. src/modules/ElasticVote/SnapshotAPI.js
3. src/modules/ElasticVote/SnapshotProposal.js
4. src/modules/ElasticVote/SnapshotVote.js


I would then look at index.js and see what could be removed there. I would expect a fair amount of cleanup in that file as well.

2021-10-27 04:33 UTC, lrsaturnino commented
@0xean I removed some more files and old code. I've done extensive test coverage. Still, I would be glad if you could take a look at it because I removed a fairly good amount of sensible code.

The App needs the branch https://github.com/elasticdao/app/tree/remove-old-node-code

2021-10-27 13:17 UTC, 0xean reviewed
Looks good! Checking to make sure it works against the app

2021-10-27 13:21 UTC, 0xean approved these changes

2021-10-27 14:35 UTC, merged